/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    startSidebar: [
        {
            type: 'category',
            link: {
                type: 'generated-index',
                title: 'Getting started on SCNX',
                description: 'Easily get started on SCNX - here you\'ll find all guides you need.',
                slug: '/intro'
            },
            label: 'Getting Started',
            collapsible: false,
            items: [
                {
                    type: 'doc',
                    id: 'setup'
                },
                {
                    type: 'doc',
                    id: 'custom-bot'
                },
                {
                    type: 'doc',
                    id: 'modmail'
                }
            ]
        },
        {
            type: 'category',
            label: 'Detailed documentation',
            items: [
                {
                    type: 'doc',
                    label: 'Custom-Bot',
                    id: 'custom-bot/intro'
                },
                {
                    type: 'doc',
                    label: 'SCNX',
                    id: 'scnx/intro'
                },
                {
                    type: 'doc',
                    label: 'Modmail-Bot',
                    id: 'modmail/intro'
                }
            ]
        }
    ],
    customBotSidebar: [
        {
            type: 'autogenerated',
            dirName: 'custom-bot'
        }
    ],
    modmailSidebar: [
        {
            type: 'autogenerated',
            dirName: 'modmail'
        }
    ],
    scnxSidebar: [
        {
            type: 'autogenerated',
            dirName: 'scnx'
        }
    ]
};

module.exports = sidebars;