/*
Internally, this way of importing module icons is configured to reduce load size. In this built with docosarus, this increases it drastically. This should get replaced by deferred loading at some point instead of bundling.
 */
import {
    faArrowUp19,
    faBadgeCheck,
    faBank,
    faBell,
    faBorderAll,
    faBox,
    faCalendar,
    faCalendarDays,
    faCheckToSlot,
    faCircleChevronUp,
    faCircleInfo,
    faClockRotateLeft,
    faCode,
    faCodeBranch,
    faCommentDots,
    faComments as faSolidComments,
    faDoorOpen,
    faFaceSmile,
    faFileCirclePlus,
    faFireFlameCurved,
    faFolder,
    faGears,
    faHandScissors,
    faHashtag,
    faHourglassHalf,
    faLaughSquint,
    faListDropdown, faLock,
    faMessages,
    faMousePointer,
    faPlus,
    faPuzzlePiece,
    faRankingStar,
    faReel,
    faRightFromBracket,
    faRobot,
    faRss,
    faShield,
    faSignInAlt,
    faSlashForward,
    faStar,
    faStream,
    faTableCells,
    faTerminal,
    faThumbtack,
    faTools,
    faUser,
    faUsers,
    faWebhook,
    faCreditCard,
    faServer,
    faEnvelope,
    faEnvelopeOpen,
    faBug,
    faLifeRing,
    faHeadset,
    faReceipt,
    faWrench,
    faCircleQuestion,
    faBullseye,
    faDatabase,
    faKey,
    faGavel,
    faBan,
    faMoneyBill,
    faScaleBalanced,
    faFileLines,
    faHandshake,
    faChartLine,
    faGlobe,
    faMicrophone,
    faMusic,
    faGamepad,
    faShoppingCart,
    faCrown,
    faMedal,
    faTrophy,
    faBookOpen,
    faGraduationCap,
    faMapMarkerAlt,
    faLink,
    faShareNodes,
    faFilter,
    faMagnifyingGlass,
    faChartPie,
    faChartBar,
    faBolt,
    faWandMagicSparkles,
    faShieldHalved,
    faUserShield,
    faLanguage,
    faEarthAmericas,
    faPaintbrush,
    faObjectGroup,
    faLayerGroup,
    faSitemap,
    faNetworkWired,
    faCloud,
    faDownload,
    faUpload,
    faFolderOpen,
    faNewspaper,
    faBlog,
    faPenNib,
    faAt,
    faPhone,
    faLocationDot,
    faHouse,
    faStore,
    faCartShopping,
    faPercent,
    faCoins,
    faWallet,
    faChartSimple,
    faArrowTrendUp,
    faGauge,
    faSpinner,
    faCircleCheck,
    faCircleXmark,
    faEye,
    faEyeSlash,
    faBellOn,
    faHeart,
    faThumbsUp,
    faAward,
    faPartyHorn,
    faSparkles,
    faMagic,
    faInbox,
    faReply,
    faReplyAll,
    faPaperPlane,
    faEnvelopesBulk,
    faFax,
    faHammer,
    faShieldExclamation,
    faUserSlash,
    faUserXmark,
    faUserCheck,
    faUserLock,
    faHandMiddleFinger,
    faOctagonExclamation,
    faCamera,
    faVideo,
    faFilm,
    faImages,
    faPhotoFilm,
    faVolumeOff,
    faVolumeLow,
    faVolumeXmark,
    faPodcast,
    faRadio,
    faHeadphones,
    faArrowRight,
    faArrowLeft,
    faArrowUp,
    faArrowDown,
    faAnglesRight,
    faAnglesLeft,
    faChevronRight,
    faChevronLeft,
    faArrowsRotate,
    faRotate,
    faExpand,
    faCompress,
    faMaximize,
    faMinimize,
    faUpRightAndDownLeftFromCenter,
    faFile,
    faFilePdf,
    faFileImage,
    faFileCode,
    faFileZipper,
    faFileExport,
    faFileImport,
    faFileArrowUp,
    faFileArrowDown,
    faFileCsv,
    faFileExcel,
    faFileWord,
    faCopy,
    faPaste,
    faScissors,
    faTrash,
    faClock,
    faStopwatch,
    faTimer,
    faCalendarCheck,
    faCalendarPlus,
    faCalendarMinus,
    faCalendarXmark,
    faFolderPlus,
    faFolderMinus,
    faFolderTree,
    faBoxArchive,
    faBookmark,
    faTag,
    faList,
    faListOl,
    faListCheck,
    faTableList,
    faGripVertical,
    faSort,
    faSortUp,
    faSortDown,
    faGear,
    faSliders,
    faToggleOn,
    faToggleOff,
    faEllipsis,
    faEllipsisVertical,
    faBars,
    faCircleHalfStroke,
    faFaceGrin,
    faFaceLaugh,
    faFaceSadTear,
    faFaceAngry,
    faFaceSurprise,
    faFaceMeh,
    faHandsClapping,
    faFire,
    faCodeMerge,
    faCodePullRequest,
    faCodeCommit,
    faCodeFork,
    faBracketsCurly,
    faMicrochip,
    faCubes,
    faPlug,
    faBriefcase,
    faBuilding,
    faIndustry,
    faLandmark,
    faScroll,
    faStamp,
    faSignature,
    faFileContract,
    faFileInvoice,
    faFileInvoiceDollar,
    faSun,
    faMoon,
    faCloudSun,
    faCloudMoon,
    faSnowflake,
    faDroplet,
    faLeaf,
    faTree,
    faSeedling,
    faFlower,
    faHeartPulse,
    faStethoscope,
    faSyringe,
    faPills,
    faShieldVirus,
    faVirusSlash,
    faQrcode,
    faBarcode,
    faFingerprint,
    faRocket,
    faPaperclip,
    faMagnifyingGlassPlus,
    faMagnifyingGlassMinus,
    faWifi,
    faSignal,
    faBattery,
    faPowerOff,
    faDesktop,
    faMobile,
    faTablet,
    faLaptop,
    faPrint,
    faKeyboard,
    faChess,
    faChessPawn,
    faChessKnight,
    faChessRook,
    faChessBishop,
    faChessKing,
    faChessQueen,
    faChessBoard,
    faPuzzle,
    faDragon,
    faGhost,
    faHatWizard,
    faDungeon,
    faWandSparkles,
    faDiceOne,
    faDiceTwo,
    faDiceThree,
    faDiceFour,
    faDiceSix,
    faJoystick,
    faDollarSign,
    faEuroSign,
    faYenSign,
    faSterlingSign,
    faBitcoinSign,
    faMoneyBillWave,
    faMoneyBillTransfer,
    faMoneyBillTrendUp,
    faMoneyCheck,
    faMoneyCheckDollar,
    faPiggyBank,
    faSackDollar,
    faVault,
    faCashRegister,
    faHandHoldingDollar,
    faCloudRain,
    faCloudBolt,
    faWind,
    faTemperatureHigh,
    faTemperatureLow,
    faTemperatureHalf,
    faUmbrella,
    faRainbow,
    faIcicles,
    faMeteor,
    faTornado,
    faHurricane,
    faSmog,
    faMugHot,
    faCoffee,
    faPizzaSlice,
    faHamburger,
    faCookie,
    faIceCream,
    faCandyCane,
    faAppleWhole,
    faLemon,
    faCarrot,
    faUtensils,
    faWineGlass,
    faBeer,
    faChampagneGlasses,
    faMartiniGlass,
    faCar,
    faBus,
    faTrain,
    faPlane,
    faShip,
    faBicycle,
    faMotorcycle,
    faTruck,
    faTaxi,
    faHelicopter,
    faJetFighter,
    faSpaceShuttle,
    faAnchor,
    faCompass,
    faBaseball,
    faBasketball,
    faFootball,
    faFutbol,
    faGolfBall,
    faTableTennis,
    faBowlingBall,
    faVolleyball,
    faDumbbell,
    faPersonRunning,
    faPersonSwimming,
    faPersonBiking,
    faPersonSkiing,
    faPersonHiking,
    faChalkboard,
    faChalkboardUser,
    faSchool,
    faPenRuler,
    faRuler,
    faCalculator,
    faFlask,
    faAtom,
    faMicroscope,
    faDna,
    faBrain,
    faLaptopCode,
    faWheelchair,
    faUniversalAccess,
    faSignLanguage,
    faEarListen,
    faHandDots,
    faPersonCane,
    faCircle,
    faSquare,
    faTriangle,
    faDiamond,
    faPentagon,
    faHexagon,
    faOctagon,
    faStarHalf,
    faCross,
    faYinYang,
    faInfinity,
    faOm,
    faDog,
    faCat,
    faHorse,
    faFish,
    faDove,
    faCrow,
    faSpider,
    faWorm,
    faShrimp,
    faOtter,
    faHippo,
    faFrog,
    faKiwiBird,
    faMask,
    faGlasses,
    faHatCowboy,
    faHelmetSafety,
    faCertificate,
    faRibbon,
    faMedkit,
    faFirstAid,
    faBandage,
    faCrutch,
    faBone,
    faSkull,
    faSkullCrossbones,
    faBiohazard,
    faRadiation,
    faArrowUpFromBracket,
    faArrowRightFromBracket,
    faArrowDownToLine,
    faArrowUpRightFromSquare,
    faArrowPointer,
    faArrowRotateLeft,
    faArrowRotateRight,
    faArrowUpLong,
    faArrowDownLong,
    faArrowRightLong,
    faArrowLeftLong,
    faArrowsTurnToDots,
    faArrowsSpin,
    faArrowsLeftRight,
    faArrowsUpDown,
    faChevronUp,
    faChevronDown,
    faAnglesUp,
    faAnglesDown,
    faArrowUpFromLine,
    faArrowDownFromLine,
    faArrowRightToLine,
    faArrowLeftToLine,
    faBold,
    faItalic,
    faUnderline,
    faStrikethrough,
    faAlignLeft,
    faAlignCenter,
    faAlignRight,
    faAlignJustify,
    faIndent,
    faOutdent,
    faQuoteLeft,
    faQuoteRight,
    faSubscript,
    faSuperscript,
    faTextSlash,
    faSpellCheck,
    faFont,
    faHeading,
    faParagraph,
    faTextWidth,
    faTextHeight,
    faHighlighter,
    faMinus,
    faXmark,
    faDivide,
    faEquals,
    faNotEqual,
    faGreaterThan,
    faLessThan,
    faSquareRoot,
    faMap,
    faMapPin,
    faMapLocationDot,
    faMapLocation,
    faStreetView,
    faMountain,
    faMountainSun,
    faWater,
    faSwimmingPool,
    faUmbrellaBeach,
    faPersonWalking,
    faBridge,
    faRoad,
    faCity,
    faHandPointUp,
    faHandPointDown,
    faHandPointLeft,
    faHandPointRight,
    faHandPeace,
    faHandFist,
    faHandBackFist,
    faThumbsDown,
    faHandHolding,
    faHandHoldingHeart,
    faHandshakeAngle,
    faHandSparkles,
    faHands,
    faAnchorCircleCheck,
    faBellConcierge,
    faBroomBall,
    faBucket,
    faCartPlus,
    faCartArrowDown,
    faChair,
    faCouch,
    faHouseLaptop,
    faJar,
    faKitchenSet,
    faLightbulb as faSolidLightbulb,
    faMagnet,
    faObjectUngroup,
    faPenToSquare,
    faRulerCombined,
    faShapes,
    faSwatchbook,
    faToolbox,
    faLockOpen,
    faUnlock,
    faPassport,
    faIdBadge,
    faIdCard,
    faUserGraduate,
    faUserDoctor,
    faUserNinja,
    faUserAstronaut,
    faSpaghettiMonsterFlying,
    faPoo,
    faPoop,
    faAlien,
    faVirus,
    faBacteria,
    faExplosion,
    faBomb,
    faPersonFalling,
    faHandcuffs,
    faPlugCircleBolt,
    faPlugCircleCheck,
    faGem,
    faBookAtlas,
    faBookBible,
    faBookJournalWhills,
    faBookSkull,
    faBookQuran,
    faBookTanakh,
    faCloudArrowUp,
    faCloudArrowDown,
    faCirclePlus,
    faCircleMinus,
    faCircleArrowRight,
    faCircleArrowLeft,
    faCircleArrowUp,
    faCircleArrowDown,
    faCircleDot,
    faCircleNotch,
    faCirclePlay,
    faCirclePause,
    faCircleStop,
    faSquarePlus,
    faSquareMinus,
    faSquareCheck,
    faSquareXmark,
    faSquareArrowUpRight,
    faSquarePollVertical,
    faSquarePen,
    faPlay,
    faPause,
    faStop,
    faForward,
    faBackward,
    faForwardStep,
    faBackwardStep,
    faShuffle,
    faRepeat,
    faRecordVinyl,
    faWindowMaximize,
    faWindowMinimize,
    faWindowRestore,
    faCubesStacked,
    faBoxOpen,
    faBoxesStacked,
    faHandshakeSimple,
    faScaleUnbalanced,
    faScaleUnbalancedFlip,
    faShieldCheck,
    faShieldCat,
    faShieldDog,
    faHouseFlag,
    faHouseFloodWater,
    faHouseMedical,
    faTowerBroadcast,
    faTowerObservation,
    faTowerCell,
    faArrowUpWideShort,
    faArrowDownWideShort,
    faArrowUpShortWide,
    faArrowDownShortWide,
    faArrowUpAZ,
    faArrowDownAZ,
    faWaterLadder,
    faPersonDrowning,
    faEarthEurope,
    faEarthAsia,
    faEarthAfrica,
    faEarthOceania,
    faSatellite,
    faSatelliteDish,
    faRadar,
    faUserGroup,
    faUserClock,
    faUserMinus,
    faMessage,
    faMessageDots,
    faMessageLines,
    faMessagePlus,
    faMessageMinus,
    faMessageCheck,
    faMessageXmark,
    faFileShield,
    faFileLock,
    faFilePen,
    faFileCheck,
    faFileMinus,
    faFilePlus,
    faPen,
    faPenClip,
    faPenFancy,
    faPenLine,
    faEraser,
    faMarker,
    faNoteSticky,
    faNotebook,
    faClipboardList,
    faTableColumns,
    faTableLayout,
    faGaugeHigh,
    faGaugeSimple,
    faGaugeSimpleHigh,
    faSpiderWeb,
    faCandleHolder,
    faFlagCheckered,
    faFlagSwallowtail,
    faPersonDigging,
    faHelmetBattle,
    faSwords,
    faSword,
    faAxe,
    faAxeBattle,
    faBowArrow,
    faCrosshairs,
    faTreasureChest
} from '@fortawesome/pro-solid-svg-icons';
import {
    faBellSlash,
    faComment,
    faComments,
    faLightbulb,
    faSmile,
    faTrashCan,
    faUserCircle
} from '@fortawesome/pro-regular-svg-icons';
import {
    faDiscord,
    faFacebook,
    faInstagram,
    faMastodon,
    faReddit,
    faThreads,
    faTiktok,
    faTwitch,
    faXTwitter,
    faYoutube
} from '@fortawesome/free-brands-svg-icons';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {
    faAlarmExclamation,
    faBellExclamation,
    faBlockBrick,
    faBroom,
    faBullhorn,
    faCakeCandles,
    faCardsBlank,
    faClipboard,
    faClipboardCheck,
    faClipboardQuestion,
    faClipboardUser,
    faCommentsQuestion,
    faCommentsQuestionCheck,
    faDice,
    faDiceD20,
    faDiceFive,
    faFileUser,
    faFlag,
    faGift,
    faGun,
    faHammerCrash,
    faIcons,
    faImage,
    faInfoCircle,
    faListUl,
    faMessageBot,
    faMoonStars,
    faPalette,
    faPollPeople,
    faScrewdriverWrench,
    faTags,
    faTickets,
    faTreeChristmas,
    faTriangleExclamation,
    faUserGear,
    faUserPen,
    faUserPlus,
    faUserSecret,
    faUsersViewfinder,
    faUserTag,
    faUserTie,
    faVolumeHigh,
    faShield as faDuotoneShield,
    faStar as faDuotoneStar,
    faHeart as faDuotoneHeart,
    faBell as faDuotoneBell,
    faGear as faDuotoneGear,
    faUser as faDuotoneUser,
    faUsers as faDuotoneUsers,
    faEnvelope as faDuotoneEnvelope,
    faLock as faDuotoneLock,
    faKey as faDuotoneKey,
    faBolt as faDuotoneBolt,
    faFire as faDuotoneFire,
    faRocket as faDuotoneRocket,
    faCrown as faDuotoneCrown,
    faTrophy as faDuotoneTrophy,
    faMedal as faDuotoneMedal,
    faGem as faDuotoneGem,
    faWandMagicSparkles as faDuotoneWandMagicSparkles,
    faBrain as faDuotoneBrain,
    faRobot as faDuotoneRobot,
    faGamepad as faDuotoneGamepad,
    faMusic as faDuotoneMusic,
    faCamera as faDuotoneCamera,
    faGlobe as faDuotoneGlobe,
    faCloud as faDuotoneCloud,
    faServer as faDuotoneServer,
    faDatabase as faDuotoneDatabase,
    faCode as faDuotoneCode,
    faTerminal as faDuotoneTerminal,
    faBug as faDuotoneBug,
    faChartLine as faDuotoneChartLine,
    faChartPie as faDuotoneChartPie,
    faGauge as faDuotoneGauge,
    faCalendar as faDuotoneCalendar,
    faClock as faDuotoneClock,
    faBookmark as faDuotoneBookmark,
    faFolder as faDuotoneFolder,
    faFile as faDuotoneFile,
    faCircleCheck as faDuotoneCircleCheck,
    faCircleXmark as faDuotoneCircleXmark,
    faShieldHalved as faDuotoneShieldHalved,
    faEye as faDuotoneEye,
    faComments as faDuotoneComments,
    faHashtag as faDuotoneHashtag,
    faAt as faDuotoneAt,
    faLink as faDuotoneLink,
    faQrcode as faDuotoneQrcode,
    faPuzzlePiece as faDuotonePuzzlePiece
} from '@fortawesome/pro-duotone-svg-icons';

export const icons = {
    'fas fa-dice': faDice,
    'fas fa-tools': faTools,
    'fas fa-dice-d20': faDiceD20,
    'far fa-bell-slash': faBellSlash,
    'far fa-slash': faSlashForward,
    'far fa-bell': faBell,
    'far fa-code': faCode,
    'far fa-robot': faRobot,
    'fas fa-right-from-bracket': faRightFromBracket,
    'fa-regular fa-trash-can': faTrashCan,
    'fas fa-comment-dots': faCommentDots,
    'fas fa-bullhorn': faBullhorn,
    'far fa-smile': faSmile,
    'fa-regular fa-comment': faComment,
    'fa fa-bell-exclamation': faBellExclamation,
    'far fa-user-circle': faUserCircle,
    'far fa-image': faImage,
    'fa-solid fa-user': faUser,
    'fa-duotone fa-regular fa-triangle-exclamation': faTriangleExclamation,
    'fa-regular fa-clock-rotate-left': faClockRotateLeft,
    'fa-solid fa-shield': faShield,
    'fa-solid fa-badge-check': faBadgeCheck,
    'fa-solid fa-users': faUsers,
    'fa fa-message-bot': faMessageBot,
    'fa fa-messages': faMessages,
    'fa fa-file-user': faFileUser,
    'far fa-icons': faIcons,
    'fas fa-birthday-cake': faCakeCandles,
    'fas fa-stream': faStream,
    'fas fa-arrow-up-1-9': faArrowUp19,
    'fa-solid fa-bank': faBank,
    'fa-solid fa-calendar-days': faCalendarDays,
    'fa-solid fa-calendar': faCalendar,
    'fas fa-block-brick': faBlockBrick,
    'fas fa-laugh-squint': faLaughSquint,
    'fas fa-gift': faGift,
    'fa-solid fa-cards-blank': faCardsBlank,
    'fa-duotone fa-clock-alarm': faAlarmExclamation,
    'fas fa-dice-five': faDiceFive,
    'fa-solid fa-circle-info': faCircleInfo,
    'fa-solid fa-list-dropdown': faListDropdown,
    'fa-solid fa-mouse': faMousePointer,
    'fa-solid fa-user-plus': faUserPlus,
    'fas fa-lock': faLock,
    'fa-solid fa-user-pen': faUserPen,
    'fas fa-moon-stars': faMoonStars,
    'fas fa-screwdriver-wrench': faScrewdriverWrench,
    'fa-solid fa-rss': faRss,
    'fa-solid fa-scissors': faHandScissors,
    'fas fa-comments': faSolidComments,
    'far fa-comments': faComments,
    'far fa-comment': faComment,
    'fa-solid fa-clipboard-list': faClipboard,
    'fas fa-hammer': faHammerCrash,
    'fas fa-clipboard-user': faClipboardUser,
    'fas fa-clipboard-question': faClipboardQuestion,
    'fas fa-list-ul': faListUl,
    'fas fa-sign-in-alt': faSignInAlt,
    'fas fa-poll': faPollPeople,
    'fas fa-info-circle': faInfoCircle,
    'far fa-lightbulb': faLightbulb,
    'fas fa-hourglass-half': faHourglassHalf,
    'fas fa-ticket-simple': faTickets,
    'fa-brands fa-twitch': faTwitch,
    'fa-brands fa-youtube': faYoutube,
    'fa-brands fa-twitter': faXTwitter,
    'fa-brands fa-tiktok': faTiktok,
    'fa-brands fa-instagram': faInstagram,
    'fa-brands fa-facebook': faFacebook,
    'fa-brands fa-reddit': faReddit,
    'fas fa-door-open': faDoorOpen,
    'fas fa-gears': faGears,
    'fa-user-tie': faUserTie,
    'fa-brands fa-threads': faThreads,
    'fa-brands fa-mastodon': faMastodon,
    'far fa-gear': faUserGear,
    'far fa-terminal': faTerminal,
    'fa-solid fa-border-all': faBorderAll,
    'fa-solid fa-comments-question-check': faCommentsQuestionCheck,
    'fa-solid fa-icons': faIcons,
    'fa-solid fa-check-to-slot': faCheckToSlot,
    'fa-solid fa-users-viewfinder': faUsersViewfinder,
    'fa-solid fa-tags': faTags,
    'fa-solid fa-volume-high': faVolumeHigh,
    'fa-solid fa-user-tag': faUserTag,
    'fas fa-circle-chevron-up': faCircleChevronUp,
    'fa-solid fa-table-cells': faTableCells,
    'fa-solid fa-clipboard-check': faClipboardCheck,
    'fas fa-palette': faPalette,
    'fa-solid fa-puzzle-piece': faPuzzlePiece,
    'fas fa-gun': faGun,
    'fa-solid fa-flag': faFlag,
    'fas fa-ranking-stars': faRankingStar,
    'fas fa-reel': faReel,
    'fas fa-box': faBox,
    'fas fa-webhook': faWebhook,
    'fas fa-pool-people': faPollPeople,
    'fas fa-fire': faFireFlameCurved,
    'fa-duotone fa-tree-christmas': faTreeChristmas,
    'fa-sharp-duotone fa-solid fa-user-secret': faUserSecret,
    'fas fa-star': faStar,
    'fas fa-smile': faFaceSmile,
    'fas fa-thumbtack': faThumbtack,
    'fab fa-discord': faDiscord,
    'fa-solid fa-hashtag': faHashtag,
    'fa-solid fa-code-branch': faCodeBranch,
    'fa-duotone fa-broom': faBroom,
    'far fa-comment-dots': faCommentsQuestion,
    'fa-sold fa-plus': faPlus,
    'fa-solid fa-file-circle-check': faFileCirclePlus,
    'fas fa-credit-card': faCreditCard,
    'fas fa-server': faServer,
    'fas fa-envelope': faEnvelope,
    'fas fa-envelope-open': faEnvelopeOpen,
    'fas fa-bug': faBug,
    'fas fa-life-ring': faLifeRing,
    'fas fa-headset': faHeadset,
    'fas fa-receipt': faReceipt,
    'fas fa-wrench': faWrench,
    'fas fa-circle-question': faCircleQuestion,
    'fas fa-bullseye': faBullseye,
    'fas fa-database': faDatabase,
    'fas fa-key': faKey,
    'fas fa-gavel': faGavel,
    'fas fa-ban': faBan,
    'fas fa-money-bill': faMoneyBill,
    'fas fa-scale-balanced': faScaleBalanced,
    'fas fa-file-lines': faFileLines,
    'fas fa-handshake': faHandshake,
    'fas fa-chart-line': faChartLine,
    'fas fa-globe': faGlobe,
    'fas fa-microphone': faMicrophone,
    'fas fa-music': faMusic,
    'fas fa-gamepad': faGamepad,
    'fas fa-shopping-cart': faShoppingCart,
    'fas fa-crown': faCrown,
    'fas fa-medal': faMedal,
    'fas fa-trophy': faTrophy,
    'fas fa-book-open': faBookOpen,
    'fas fa-graduation-cap': faGraduationCap,
    'fas fa-map-marker-alt': faMapMarkerAlt,
    'fas fa-link': faLink,
    'fas fa-share-nodes': faShareNodes,
    'fas fa-filter': faFilter,
    'fas fa-magnifying-glass': faMagnifyingGlass,
    'fas fa-chart-pie': faChartPie,
    'fas fa-chart-bar': faChartBar,
    'fas fa-bolt': faBolt,
    'fas fa-wand-magic-sparkles': faWandMagicSparkles,
    'fas fa-shield-halved': faShieldHalved,
    'fas fa-user-shield': faUserShield,
    'fas fa-language': faLanguage,
    'fas fa-earth-americas': faEarthAmericas,
    'fas fa-paintbrush': faPaintbrush,
    'fas fa-object-group': faObjectGroup,
    'fas fa-layer-group': faLayerGroup,
    'fas fa-sitemap': faSitemap,
    'fas fa-network-wired': faNetworkWired,
    'fas fa-cloud': faCloud,
    'fas fa-download': faDownload,
    'fas fa-upload': faUpload,
    'fas fa-folder-open': faFolderOpen,
    'fas fa-newspaper': faNewspaper,
    'fas fa-blog': faBlog,
    'fas fa-pen-nib': faPenNib,
    'fas fa-at': faAt,
    'fas fa-phone': faPhone,
    'fas fa-location-dot': faLocationDot,
    'fas fa-house': faHouse,
    'fas fa-store': faStore,
    'fas fa-cart-shopping': faCartShopping,
    'fas fa-percent': faPercent,
    'fas fa-coins': faCoins,
    'fas fa-wallet': faWallet,
    'fas fa-chart-simple': faChartSimple,
    'fas fa-arrow-trend-up': faArrowTrendUp,
    'fas fa-gauge': faGauge,
    'fas fa-spinner': faSpinner,
    'fas fa-circle-check': faCircleCheck,
    'fas fa-circle-xmark': faCircleXmark,
    'fas fa-eye': faEye,
    'fas fa-eye-slash': faEyeSlash,
    'fas fa-bell-on': faBellOn,
    'fas fa-heart': faHeart,
    'fas fa-thumbs-up': faThumbsUp,
    'fas fa-award': faAward,
    'fas fa-party-horn': faPartyHorn,
    'fas fa-sparkles': faSparkles,
    'fas fa-magic': faMagic,
    'fas fa-inbox': faInbox,
    'fas fa-reply': faReply,
    'fas fa-reply-all': faReplyAll,
    'fas fa-paper-plane': faPaperPlane,
    'fas fa-envelopes-bulk': faEnvelopesBulk,
    'fas fa-fax': faFax,
    'fa-solid fa-hammer': faHammer,
    'fas fa-shield-exclamation': faShieldExclamation,
    'fas fa-user-slash': faUserSlash,
    'fas fa-user-xmark': faUserXmark,
    'fas fa-user-check': faUserCheck,
    'fas fa-user-lock': faUserLock,
    'fas fa-hand-middle-finger': faHandMiddleFinger,
    'fas fa-octagon-exclamation': faOctagonExclamation,
    'fas fa-camera': faCamera,
    'fas fa-video': faVideo,
    'fas fa-film': faFilm,
    'fas fa-images': faImages,
    'fas fa-photo-film': faPhotoFilm,
    'fas fa-volume-off': faVolumeOff,
    'fas fa-volume-low': faVolumeLow,
    'fas fa-volume-xmark': faVolumeXmark,
    'fas fa-podcast': faPodcast,
    'fas fa-radio': faRadio,
    'fas fa-headphones': faHeadphones,
    'fas fa-arrow-right': faArrowRight,
    'fas fa-arrow-left': faArrowLeft,
    'fas fa-arrow-up': faArrowUp,
    'fas fa-arrow-down': faArrowDown,
    'fas fa-angles-right': faAnglesRight,
    'fas fa-angles-left': faAnglesLeft,
    'fas fa-chevron-right': faChevronRight,
    'fas fa-chevron-left': faChevronLeft,
    'fas fa-arrows-rotate': faArrowsRotate,
    'fas fa-rotate': faRotate,
    'fas fa-expand': faExpand,
    'fas fa-compress': faCompress,
    'fas fa-maximize': faMaximize,
    'fas fa-minimize': faMinimize,
    'fas fa-up-right-and-down-left-from-center': faUpRightAndDownLeftFromCenter,
    'fas fa-file': faFile,
    'fas fa-file-pdf': faFilePdf,
    'fas fa-file-image': faFileImage,
    'fas fa-file-code': faFileCode,
    'fas fa-file-zipper': faFileZipper,
    'fas fa-file-export': faFileExport,
    'fas fa-file-import': faFileImport,
    'fas fa-file-arrow-up': faFileArrowUp,
    'fas fa-file-arrow-down': faFileArrowDown,
    'fas fa-file-csv': faFileCsv,
    'fas fa-file-excel': faFileExcel,
    'fas fa-file-word': faFileWord,
    'fas fa-copy': faCopy,
    'fas fa-paste': faPaste,
    'fas fa-scissors': faScissors,
    'fas fa-trash': faTrash,
    'fas fa-clock': faClock,
    'fas fa-stopwatch': faStopwatch,
    'fas fa-timer': faTimer,
    'fas fa-calendar-check': faCalendarCheck,
    'fas fa-calendar-plus': faCalendarPlus,
    'fas fa-calendar-minus': faCalendarMinus,
    'fas fa-calendar-xmark': faCalendarXmark,
    'fas fa-folder-plus': faFolderPlus,
    'fas fa-folder-minus': faFolderMinus,
    'fas fa-folder-tree': faFolderTree,
    'fas fa-box-archive': faBoxArchive,
    'fas fa-bookmark': faBookmark,
    'fas fa-tag': faTag,
    'fas fa-list': faList,
    'fas fa-list-ol': faListOl,
    'fas fa-list-check': faListCheck,
    'fas fa-table-list': faTableList,
    'fas fa-grip-vertical': faGripVertical,
    'fas fa-sort': faSort,
    'fas fa-sort-up': faSortUp,
    'fas fa-sort-down': faSortDown,
    'fas fa-gear': faGear,
    'fas fa-sliders': faSliders,
    'fas fa-toggle-on': faToggleOn,
    'fas fa-toggle-off': faToggleOff,
    'fas fa-ellipsis': faEllipsis,
    'fas fa-ellipsis-vertical': faEllipsisVertical,
    'fas fa-bars': faBars,
    'fas fa-circle-half-stroke': faCircleHalfStroke,
    'fas fa-face-grin': faFaceGrin,
    'fas fa-face-laugh': faFaceLaugh,
    'fas fa-face-sad-tear': faFaceSadTear,
    'fas fa-face-angry': faFaceAngry,
    'fas fa-face-surprise': faFaceSurprise,
    'fas fa-face-meh': faFaceMeh,
    'fas fa-hands-clapping': faHandsClapping,
    'fa-solid fa-fire': faFire,
    'fas fa-code-merge': faCodeMerge,
    'fas fa-code-pull-request': faCodePullRequest,
    'fas fa-code-commit': faCodeCommit,
    'fas fa-code-fork': faCodeFork,
    'fas fa-brackets-curly': faBracketsCurly,
    'fas fa-microchip': faMicrochip,
    'fas fa-cubes': faCubes,
    'fas fa-plug': faPlug,
    'fas fa-briefcase': faBriefcase,
    'fas fa-building': faBuilding,
    'fas fa-industry': faIndustry,
    'fas fa-landmark': faLandmark,
    'fas fa-scroll': faScroll,
    'fas fa-stamp': faStamp,
    'fas fa-signature': faSignature,
    'fas fa-file-contract': faFileContract,
    'fas fa-file-invoice': faFileInvoice,
    'fas fa-file-invoice-dollar': faFileInvoiceDollar,
    'fas fa-sun': faSun,
    'fas fa-moon': faMoon,
    'fas fa-cloud-sun': faCloudSun,
    'fas fa-cloud-moon': faCloudMoon,
    'fas fa-snowflake': faSnowflake,
    'fas fa-droplet': faDroplet,
    'fas fa-leaf': faLeaf,
    'fas fa-tree': faTree,
    'fas fa-seedling': faSeedling,
    'fas fa-flower': faFlower,
    'fas fa-heart-pulse': faHeartPulse,
    'fas fa-stethoscope': faStethoscope,
    'fas fa-syringe': faSyringe,
    'fas fa-pills': faPills,
    'fas fa-shield-virus': faShieldVirus,
    'fas fa-virus-slash': faVirusSlash,
    'fas fa-qrcode': faQrcode,
    'fas fa-barcode': faBarcode,
    'fas fa-fingerprint': faFingerprint,
    'fas fa-rocket': faRocket,
    'fas fa-paperclip': faPaperclip,
    'fas fa-magnifying-glass-plus': faMagnifyingGlassPlus,
    'fas fa-magnifying-glass-minus': faMagnifyingGlassMinus,
    'fas fa-wifi': faWifi,
    'fas fa-signal': faSignal,
    'fas fa-battery': faBattery,
    'fas fa-power-off': faPowerOff,
    'fas fa-desktop': faDesktop,
    'fas fa-mobile': faMobile,
    'fas fa-tablet': faTablet,
    'fas fa-laptop': faLaptop,
    'fas fa-print': faPrint,
    'fas fa-keyboard': faKeyboard,
    'fas fa-chess': faChess,
    'fas fa-chess-pawn': faChessPawn,
    'fas fa-chess-knight': faChessKnight,
    'fas fa-chess-rook': faChessRook,
    'fas fa-chess-bishop': faChessBishop,
    'fas fa-chess-king': faChessKing,
    'fas fa-chess-queen': faChessQueen,
    'fas fa-chess-board': faChessBoard,
    'fas fa-puzzle': faPuzzle,
    'fas fa-dragon': faDragon,
    'fas fa-ghost': faGhost,
    'fas fa-hat-wizard': faHatWizard,
    'fas fa-dungeon': faDungeon,
    'fas fa-wand-sparkles': faWandSparkles,
    'fas fa-dice-one': faDiceOne,
    'fas fa-dice-two': faDiceTwo,
    'fas fa-dice-three': faDiceThree,
    'fas fa-dice-four': faDiceFour,
    'fas fa-dice-six': faDiceSix,
    'fas fa-joystick': faJoystick,
    'fas fa-dollar-sign': faDollarSign,
    'fas fa-euro-sign': faEuroSign,
    'fas fa-yen-sign': faYenSign,
    'fas fa-sterling-sign': faSterlingSign,
    'fas fa-bitcoin-sign': faBitcoinSign,
    'fas fa-money-bill-wave': faMoneyBillWave,
    'fas fa-money-bill-transfer': faMoneyBillTransfer,
    'fas fa-money-bill-trend-up': faMoneyBillTrendUp,
    'fas fa-money-check': faMoneyCheck,
    'fas fa-money-check-dollar': faMoneyCheckDollar,
    'fas fa-piggy-bank': faPiggyBank,
    'fas fa-sack-dollar': faSackDollar,
    'fas fa-vault': faVault,
    'fas fa-cash-register': faCashRegister,
    'fas fa-hand-holding-dollar': faHandHoldingDollar,
    'fas fa-cloud-rain': faCloudRain,
    'fas fa-cloud-bolt': faCloudBolt,
    'fas fa-wind': faWind,
    'fas fa-temperature-high': faTemperatureHigh,
    'fas fa-temperature-low': faTemperatureLow,
    'fas fa-temperature-half': faTemperatureHalf,
    'fas fa-umbrella': faUmbrella,
    'fas fa-rainbow': faRainbow,
    'fas fa-icicles': faIcicles,
    'fas fa-meteor': faMeteor,
    'fas fa-tornado': faTornado,
    'fas fa-hurricane': faHurricane,
    'fas fa-smog': faSmog,
    'fas fa-mug-hot': faMugHot,
    'fas fa-mug-saucer': faCoffee,
    'fas fa-pizza-slice': faPizzaSlice,
    'fas fa-burger': faHamburger,
    'fas fa-cookie': faCookie,
    'fas fa-ice-cream': faIceCream,
    'fas fa-candy-cane': faCandyCane,
    'fas fa-apple-whole': faAppleWhole,
    'fas fa-lemon': faLemon,
    'fas fa-carrot': faCarrot,
    'fas fa-utensils': faUtensils,
    'fas fa-wine-glass': faWineGlass,
    'fas fa-beer-mug-empty': faBeer,
    'fas fa-champagne-glasses': faChampagneGlasses,
    'fas fa-martini-glass': faMartiniGlass,
    'fas fa-car': faCar,
    'fas fa-bus': faBus,
    'fas fa-train': faTrain,
    'fas fa-plane': faPlane,
    'fas fa-ship': faShip,
    'fas fa-bicycle': faBicycle,
    'fas fa-motorcycle': faMotorcycle,
    'fas fa-truck': faTruck,
    'fas fa-taxi': faTaxi,
    'fas fa-helicopter': faHelicopter,
    'fas fa-jet-fighter': faJetFighter,
    'fas fa-shuttle-space': faSpaceShuttle,
    'fas fa-anchor': faAnchor,
    'fas fa-compass': faCompass,
    'fas fa-baseball': faBaseball,
    'fas fa-basketball': faBasketball,
    'fas fa-football': faFootball,
    'fas fa-futbol': faFutbol,
    'fas fa-golf-ball-tee': faGolfBall,
    'fas fa-table-tennis-paddle-ball': faTableTennis,
    'fas fa-bowling-ball': faBowlingBall,
    'fas fa-volleyball': faVolleyball,
    'fas fa-dumbbell': faDumbbell,
    'fas fa-person-running': faPersonRunning,
    'fas fa-person-swimming': faPersonSwimming,
    'fas fa-person-biking': faPersonBiking,
    'fas fa-person-skiing': faPersonSkiing,
    'fas fa-person-hiking': faPersonHiking,
    'fas fa-chalkboard': faChalkboard,
    'fas fa-chalkboard-user': faChalkboardUser,
    'fas fa-school': faSchool,
    'fas fa-pen-ruler': faPenRuler,
    'fas fa-ruler': faRuler,
    'fas fa-calculator': faCalculator,
    'fas fa-flask': faFlask,
    'fas fa-atom': faAtom,
    'fas fa-microscope': faMicroscope,
    'fas fa-dna': faDna,
    'fas fa-brain': faBrain,
    'fas fa-laptop-code': faLaptopCode,
    'fas fa-wheelchair': faWheelchair,
    'fas fa-universal-access': faUniversalAccess,
    'fas fa-hands': faSignLanguage,
    'fas fa-ear-listen': faEarListen,
    'fas fa-hand-dots': faHandDots,
    'fas fa-person-cane': faPersonCane,
    'fas fa-circle': faCircle,
    'fas fa-square': faSquare,
    'fas fa-triangle': faTriangle,
    'fas fa-diamond': faDiamond,
    'fas fa-pentagon': faPentagon,
    'fas fa-hexagon': faHexagon,
    'fas fa-octagon': faOctagon,
    'fas fa-star-half': faStarHalf,
    'fas fa-cross': faCross,
    'fas fa-yin-yang': faYinYang,
    'fas fa-infinity': faInfinity,
    'fas fa-om': faOm,
    'fas fa-dog': faDog,
    'fas fa-cat': faCat,
    'fas fa-horse': faHorse,
    'fas fa-fish': faFish,
    'fas fa-dove': faDove,
    'fas fa-crow': faCrow,
    'fas fa-spider': faSpider,
    'fas fa-worm': faWorm,
    'fas fa-shrimp': faShrimp,
    'fas fa-otter': faOtter,
    'fas fa-hippo': faHippo,
    'fas fa-frog': faFrog,
    'fas fa-kiwi-bird': faKiwiBird,
    'fas fa-mask': faMask,
    'fas fa-glasses': faGlasses,
    'fas fa-hat-cowboy': faHatCowboy,
    'fas fa-helmet-safety': faHelmetSafety,
    'fas fa-certificate': faCertificate,
    'fas fa-ribbon': faRibbon,
    'fas fa-suitcase-medical': faMedkit,
    'fas fa-kit-medical': faFirstAid,
    'fas fa-bandage': faBandage,
    'fas fa-crutch': faCrutch,
    'fas fa-bone': faBone,
    'fas fa-skull': faSkull,
    'fas fa-skull-crossbones': faSkullCrossbones,
    'fas fa-biohazard': faBiohazard,
    'fas fa-radiation': faRadiation,
    // Arrows & Direction
    'fas fa-arrow-up-from-bracket': faArrowUpFromBracket,
    'fas fa-arrow-right-from-bracket': faArrowRightFromBracket,
    'fas fa-arrow-down-to-line': faArrowDownToLine,
    'fas fa-arrow-up-right-from-square': faArrowUpRightFromSquare,
    'fas fa-arrow-pointer': faArrowPointer,
    'fas fa-arrow-rotate-left': faArrowRotateLeft,
    'fas fa-arrow-rotate-right': faArrowRotateRight,
    'fas fa-arrow-up-long': faArrowUpLong,
    'fas fa-arrow-down-long': faArrowDownLong,
    'fas fa-arrow-right-long': faArrowRightLong,
    'fas fa-arrow-left-long': faArrowLeftLong,
    'fas fa-arrows-turn-to-dots': faArrowsTurnToDots,
    'fas fa-arrows-spin': faArrowsSpin,
    'fas fa-arrows-left-right': faArrowsLeftRight,
    'fas fa-arrows-up-down': faArrowsUpDown,
    'fas fa-chevron-up': faChevronUp,
    'fas fa-chevron-down': faChevronDown,
    'fas fa-angles-up': faAnglesUp,
    'fas fa-angles-down': faAnglesDown,
    'fas fa-arrow-up-from-line': faArrowUpFromLine,
    'fas fa-arrow-down-from-line': faArrowDownFromLine,
    'fas fa-arrow-right-to-line': faArrowRightToLine,
    'fas fa-arrow-left-to-line': faArrowLeftToLine,
    'fas fa-arrow-up-wide-short': faArrowUpWideShort,
    'fas fa-arrow-down-wide-short': faArrowDownWideShort,
    'fas fa-arrow-up-short-wide': faArrowUpShortWide,
    'fas fa-arrow-down-short-wide': faArrowDownShortWide,
    'fas fa-arrow-up-a-z': faArrowUpAZ,
    'fas fa-arrow-down-a-z': faArrowDownAZ,
    // Text & Editor
    'fas fa-bold': faBold,
    'fas fa-italic': faItalic,
    'fas fa-underline': faUnderline,
    'fas fa-strikethrough': faStrikethrough,
    'fas fa-align-left': faAlignLeft,
    'fas fa-align-center': faAlignCenter,
    'fas fa-align-right': faAlignRight,
    'fas fa-align-justify': faAlignJustify,
    'fas fa-indent': faIndent,
    'fas fa-outdent': faOutdent,
    'fas fa-quote-left': faQuoteLeft,
    'fas fa-quote-right': faQuoteRight,
    'fas fa-subscript': faSubscript,
    'fas fa-superscript': faSuperscript,
    'fas fa-text-slash': faTextSlash,
    'fas fa-spell-check': faSpellCheck,
    'fas fa-font': faFont,
    'fas fa-heading': faHeading,
    'fas fa-paragraph': faParagraph,
    'fas fa-text-width': faTextWidth,
    'fas fa-text-height': faTextHeight,
    'fas fa-highlighter': faHighlighter,
    'fas fa-pen': faPen,
    'fas fa-pen-clip': faPenClip,
    'fas fa-pen-fancy': faPenFancy,
    'fas fa-pen-line': faPenLine,
    'fas fa-pen-to-square': faPenToSquare,
    'fas fa-eraser': faEraser,
    'fas fa-marker': faMarker,
    'fas fa-note-sticky': faNoteSticky,
    'fas fa-notebook': faNotebook,
    // Math & Numbers
    'fas fa-minus': faMinus,
    'fas fa-xmark': faXmark,
    'fas fa-divide': faDivide,
    'fas fa-equals': faEquals,
    'fas fa-not-equal': faNotEqual,
    'fas fa-greater-than': faGreaterThan,
    'fas fa-less-than': faLessThan,
    'fas fa-square-root': faSquareRoot,
    // Maps & Places
    'fas fa-map': faMap,
    'fas fa-map-pin': faMapPin,
    'fas fa-map-location-dot': faMapLocationDot,
    'fas fa-map-location': faMapLocation,
    'fas fa-street-view': faStreetView,
    'fas fa-mountain': faMountain,
    'fas fa-mountain-sun': faMountainSun,
    'fas fa-water': faWater,
    'fas fa-swimming-pool': faSwimmingPool,
    'fas fa-umbrella-beach': faUmbrellaBeach,
    'fas fa-person-walking': faPersonWalking,
    'fas fa-bridge': faBridge,
    'fas fa-road': faRoad,
    'fas fa-city': faCity,
    'fas fa-earth-europe': faEarthEurope,
    'fas fa-earth-asia': faEarthAsia,
    'fas fa-earth-africa': faEarthAfrica,
    'fas fa-earth-oceania': faEarthOceania,
    // Hands & Gestures
    'fas fa-hand-point-up': faHandPointUp,
    'fas fa-hand-point-down': faHandPointDown,
    'fas fa-hand-point-left': faHandPointLeft,
    'fas fa-hand-point-right': faHandPointRight,
    'fas fa-hand-peace': faHandPeace,
    'fas fa-hand-fist': faHandFist,
    'fas fa-hand-back-fist': faHandBackFist,
    'fas fa-thumbs-down': faThumbsDown,
    'fas fa-hand-holding': faHandHolding,
    'fas fa-hand-holding-heart': faHandHoldingHeart,
    'fas fa-handshake-angle': faHandshakeAngle,
    'fas fa-hand-sparkles': faHandSparkles,
    'fas fa-hands-asl-interpreting': faHands,
    // Objects
    'fas fa-anchor-circle-check': faAnchorCircleCheck,
    'fas fa-bell-concierge': faBellConcierge,
    'fas fa-broom-ball': faBroomBall,
    'fas fa-bucket': faBucket,
    'fas fa-cart-plus': faCartPlus,
    'fas fa-cart-arrow-down': faCartArrowDown,
    'fas fa-chair': faChair,
    'fas fa-couch': faCouch,
    'fas fa-house-laptop': faHouseLaptop,
    'fas fa-jar': faJar,
    'fas fa-kitchen-set': faKitchenSet,
    'fas fa-lightbulb': faSolidLightbulb,
    'fas fa-magnet': faMagnet,
    'fas fa-object-ungroup': faObjectUngroup,
    'fas fa-ruler-combined': faRulerCombined,
    'fas fa-shapes': faShapes,
    'fas fa-swatchbook': faSwatchbook,
    'fas fa-toolbox': faToolbox,
    'fas fa-treasure-chest': faTreasureChest,
    'fas fa-candle-holder': faCandleHolder,
    // Security & Identity
    'fas fa-lock-open': faLockOpen,
    'fas fa-unlock': faUnlock,
    'fas fa-passport': faPassport,
    'fas fa-id-badge': faIdBadge,
    'fas fa-id-card': faIdCard,
    'fas fa-user-graduate': faUserGraduate,
    'fas fa-user-doctor': faUserDoctor,
    'fas fa-user-ninja': faUserNinja,
    'fas fa-user-astronaut': faUserAstronaut,
    'fas fa-user-group': faUserGroup,
    'fas fa-user-clock': faUserClock,
    'fas fa-user-minus': faUserMinus,
    'fas fa-handcuffs': faHandcuffs,
    'fas fa-shield-check': faShieldCheck,
    'fas fa-shield-cat': faShieldCat,
    'fas fa-shield-dog': faShieldDog,
    // Misc & Fun
    'fas fa-spaghetti-monster-flying': faSpaghettiMonsterFlying,
    'fas fa-poo': faPoo,
    'fas fa-poop': faPoop,
    'fas fa-alien': faAlien,
    'fas fa-virus': faVirus,
    'fas fa-bacteria': faBacteria,
    'fas fa-explosion': faExplosion,
    'fas fa-bomb': faBomb,
    'fas fa-person-falling': faPersonFalling,
    'fas fa-plug-circle-bolt': faPlugCircleBolt,
    'fas fa-plug-circle-check': faPlugCircleCheck,
    'fas fa-spider-web': faSpiderWeb,
    // Books
    'fas fa-gem': faGem,
    'fas fa-book-atlas': faBookAtlas,
    'fas fa-book-bible': faBookBible,
    'fas fa-book-journal-whills': faBookJournalWhills,
    'fas fa-book-skull': faBookSkull,
    'fas fa-book-quran': faBookQuran,
    'fas fa-book-tanakh': faBookTanakh,
    // Cloud
    'fas fa-cloud-arrow-up': faCloudArrowUp,
    'fas fa-cloud-arrow-down': faCloudArrowDown,
    // Circle variants
    'fas fa-circle-plus': faCirclePlus,
    'fas fa-circle-minus': faCircleMinus,
    'fas fa-circle-arrow-right': faCircleArrowRight,
    'fas fa-circle-arrow-left': faCircleArrowLeft,
    'fas fa-circle-arrow-up': faCircleArrowUp,
    'fas fa-circle-arrow-down': faCircleArrowDown,
    'fas fa-circle-dot': faCircleDot,
    'fas fa-circle-notch': faCircleNotch,
    'fas fa-circle-play': faCirclePlay,
    'fas fa-circle-pause': faCirclePause,
    'fas fa-circle-stop': faCircleStop,
    // Square variants
    'fas fa-square-plus': faSquarePlus,
    'fas fa-square-minus': faSquareMinus,
    'fas fa-square-check': faSquareCheck,
    'fas fa-square-xmark': faSquareXmark,
    'fas fa-square-arrow-up-right': faSquareArrowUpRight,
    'fas fa-square-poll-vertical': faSquarePollVertical,
    'fas fa-square-pen': faSquarePen,
    // Media playback
    'fas fa-play': faPlay,
    'fas fa-pause': faPause,
    'fas fa-stop': faStop,
    'fas fa-forward': faForward,
    'fas fa-backward': faBackward,
    'fas fa-forward-step': faForwardStep,
    'fas fa-backward-step': faBackwardStep,
    'fas fa-shuffle': faShuffle,
    'fas fa-repeat': faRepeat,
    'fas fa-record-vinyl': faRecordVinyl,
    // Windows
    'fas fa-window-maximize': faWindowMaximize,
    'fas fa-window-minimize': faWindowMinimize,
    'fas fa-window-restore': faWindowRestore,
    // Containers
    'fas fa-cubes-stacked': faCubesStacked,
    'fas fa-box-open': faBoxOpen,
    'fas fa-boxes-stacked': faBoxesStacked,
    // Legal & Business
    'fas fa-handshake-simple': faHandshakeSimple,
    'fas fa-scale-unbalanced': faScaleUnbalanced,
    'fas fa-scale-unbalanced-flip': faScaleUnbalancedFlip,
    'fas fa-clipboard-list': faClipboardList,
    // Houses
    'fas fa-house-flag': faHouseFlag,
    'fas fa-house-flood-water': faHouseFloodWater,
    'fas fa-house-medical': faHouseMedical,
    // Towers & Communication
    'fas fa-tower-broadcast': faTowerBroadcast,
    'fas fa-tower-observation': faTowerObservation,
    'fas fa-tower-cell': faTowerCell,
    'fas fa-satellite': faSatellite,
    'fas fa-satellite-dish': faSatelliteDish,
    'fas fa-radar': faRadar,
    // Water & Activities
    'fas fa-water-ladder': faWaterLadder,
    'fas fa-person-drowning': faPersonDrowning,
    'fas fa-person-digging': faPersonDigging,
    // Messages
    'fas fa-message': faMessage,
    'fas fa-message-dots': faMessageDots,
    'fas fa-message-lines': faMessageLines,
    'fas fa-message-plus': faMessagePlus,
    'fas fa-message-minus': faMessageMinus,
    'fas fa-message-check': faMessageCheck,
    'fas fa-message-xmark': faMessageXmark,
    // File variants
    'fas fa-file-shield': faFileShield,
    'fas fa-file-lock': faFileLock,
    'fas fa-file-pen': faFilePen,
    'fas fa-file-check': faFileCheck,
    'fas fa-file-minus': faFileMinus,
    'fas fa-file-plus': faFilePlus,
    // Tables
    'fas fa-table-columns': faTableColumns,
    'fas fa-table-layout': faTableLayout,
    // Gauges
    'fas fa-gauge-high': faGaugeHigh,
    'fas fa-gauge-simple': faGaugeSimple,
    'fas fa-gauge-simple-high': faGaugeSimpleHigh,
    // Flags
    'fas fa-flag-checkered': faFlagCheckered,
    'fas fa-flag-swallowtail': faFlagSwallowtail,
    // Combat & Fantasy
    'fas fa-helmet-battle': faHelmetBattle,
    'fas fa-swords': faSwords,
    'fas fa-sword': faSword,
    'fas fa-axe': faAxe,
    'fas fa-axe-battle': faAxeBattle,
    'fas fa-bow-arrow': faBowArrow,
    'fas fa-crosshairs': faCrosshairs,
    // Duotone variants
    'fa-duotone fa-shield': faDuotoneShield,
    'fa-duotone fa-star': faDuotoneStar,
    'fa-duotone fa-heart': faDuotoneHeart,
    'fa-duotone fa-bell': faDuotoneBell,
    'fa-duotone fa-gear': faDuotoneGear,
    'fa-duotone fa-user': faDuotoneUser,
    'fa-duotone fa-users': faDuotoneUsers,
    'fa-duotone fa-envelope': faDuotoneEnvelope,
    'fa-duotone fa-lock': faDuotoneLock,
    'fa-duotone fa-key': faDuotoneKey,
    'fa-duotone fa-bolt': faDuotoneBolt,
    'fa-duotone fa-fire': faDuotoneFire,
    'fa-duotone fa-rocket': faDuotoneRocket,
    'fa-duotone fa-crown': faDuotoneCrown,
    'fa-duotone fa-trophy': faDuotoneTrophy,
    'fa-duotone fa-medal': faDuotoneMedal,
    'fa-duotone fa-gem': faDuotoneGem,
    'fa-duotone fa-wand-magic-sparkles': faDuotoneWandMagicSparkles,
    'fa-duotone fa-brain': faDuotoneBrain,
    'fa-duotone fa-robot': faDuotoneRobot,
    'fa-duotone fa-gamepad': faDuotoneGamepad,
    'fa-duotone fa-music': faDuotoneMusic,
    'fa-duotone fa-camera': faDuotoneCamera,
    'fa-duotone fa-globe': faDuotoneGlobe,
    'fa-duotone fa-cloud': faDuotoneCloud,
    'fa-duotone fa-server': faDuotoneServer,
    'fa-duotone fa-database': faDuotoneDatabase,
    'fa-duotone fa-code': faDuotoneCode,
    'fa-duotone fa-terminal': faDuotoneTerminal,
    'fa-duotone fa-bug': faDuotoneBug,
    'fa-duotone fa-chart-line': faDuotoneChartLine,
    'fa-duotone fa-chart-pie': faDuotoneChartPie,
    'fa-duotone fa-gauge': faDuotoneGauge,
    'fa-duotone fa-calendar': faDuotoneCalendar,
    'fa-duotone fa-clock': faDuotoneClock,
    'fa-duotone fa-bookmark': faDuotoneBookmark,
    'fa-duotone fa-folder': faDuotoneFolder,
    'fa-duotone fa-file': faDuotoneFile,
    'fa-duotone fa-circle-check': faDuotoneCircleCheck,
    'fa-duotone fa-circle-xmark': faDuotoneCircleXmark,
    'fa-duotone fa-shield-halved': faDuotoneShieldHalved,
    'fa-duotone fa-eye': faDuotoneEye,
    'fa-duotone fa-comments': faDuotoneComments,
    'fa-duotone fa-hashtag': faDuotoneHashtag,
    'fa-duotone fa-at': faDuotoneAt,
    'fa-duotone fa-link': faDuotoneLink,
    'fa-duotone fa-qrcode': faDuotoneQrcode,
    'fa-duotone fa-puzzle-piece': faDuotonePuzzlePiece
};

export default function ModuleIcon({icon, className, width = 23, hMe}) {
    return <FontAwesomeIcon icon={icons[icon] || faFolder} width={width} className={className}/>;
}