/*
Internally, this way of importing module icons is configured to reduce load size. In this built with docosarus, this increases it drastically. This should get replaced by deferred loading at some point instead of bundling.
 */

import {
    faArrowUp19,
    faBank,
    faBell,
    faBorderAll,
    faCheckToSlot,
    faCircleChevronUp,
    faCircleInfo,
    faCommentDots,
    faComments as faSolidComments,
    faDoorOpen,
    faFaceSmile,
    faFileCirclePlus,
    faFolder,
    faGears,
    faHandScissors,
    faHourglassHalf,
    faLaughSquint,
    faPuzzlePiece,
    faRankingStar,
    faRightFromBracket,
    faRss,
    faSignInAlt,
    faStar,
    faStream,
    faTableCells,
    faTerminal,
    faThumbtack,
    faTools
} from '@fortawesome/pro-solid-svg-icons';
import {
    faBellSlash,
    faComment,
    faComments,
    faLightbulb,
    faSmile,
    faTrashCan,
    faUserCircle
} from '@fortawesome/pro-regular-svg-icons';
import {
    faFacebook,
    faInstagram,
    faMastodon,
    faReddit,
    faThreads,
    faTiktok,
    faTwitch,
    faXTwitter,
    faYoutube
} from '@fortawesome/free-brands-svg-icons';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {
    faBellExclamation,
    faBlockBrick,
    faBullhorn,
    faCakeCandles,
    faCardsBlank,
    faClipboard,
    faClipboardCheck,
    faClipboardQuestion,
    faClipboardUser,
    faCommentsQuestion,
    faCommentsQuestionCheck,
    faDice,
    faDiceD20,
    faDiceFive,
    faFileUser,
    faFlag,
    faGift,
    faGun,
    faHammerCrash,
    faIcons,
    faImage,
    faInfoCircle,
    faListUl,
    faMessageBot,
    faMoonStars,
    faPalette,
    faPollPeople,
    faScrewdriverWrench,
    faTags,
    faTickets,
    faUserGear,
    faUserPen,
    faUserPlus,
    faUsersViewfinder,
    faUserTag,
    faUserTie,
    faVolumeHigh
} from '@fortawesome/pro-duotone-svg-icons';

const icons = {
    'fas fa-dice': faDice,
    'fas fa-tools': faTools,
    'fas fa-dice-d20': faDiceD20,
    'far fa-bell-slash': faBellSlash,
    'far fa-bell': faBell,
    'fas fa-right-from-bracket': faRightFromBracket,
    'fa-regular fa-trash-can': faTrashCan,
    'fas fa-comment-dots': faCommentDots,
    'fas fa-bullhorn': faBullhorn,
    'far fa-smile': faSmile,
    'fa-regular fa-comment': faComment,
    'fa fa-bell-exclamation': faBellExclamation,
    'far fa-user-circle': faUserCircle,
    'far fa-image': faImage,
    'fa fa-message-bot': faMessageBot,
    'fa fa-file-user': faFileUser,
    'far fa-icons': faIcons,
    'fas fa-birthday-cake': faCakeCandles,
    'fas fa-stream': faStream,
    'fas fa-arrow-up-1-9': faArrowUp19,
    'fa-solid fa-bank': faBank,
    'fas fa-block-brick': faBlockBrick,
    'fas fa-laugh-squint': faLaughSquint,
    'fas fa-gift': faGift,
    'fa-solid fa-cards-blank': faCardsBlank,
    'fas fa-dice-five': faDiceFive,
    'fa-solid fa-circle-info': faCircleInfo,
    'fa-solid fa-user-plus': faUserPlus,
    'fa-solid fa-user-pen': faUserPen,
    'fas fa-moon-stars': faMoonStars,
    'fas fa-screwdriver-wrench': faScrewdriverWrench,
    'fa-solid fa-rss': faRss,
    'fa-solid fa-scissors': faHandScissors,
    'fas fa-comments': faSolidComments,
    'far fa-comments': faComments,
    'far fa-comment': faComment,
    'fa-solid fa-clipboard-list': faClipboard,
    'fas fa-hammer': faHammerCrash,
    'fas fa-clipboard-user': faClipboardUser,
    'fas fa-clipboard-question': faClipboardQuestion,
    'fas fa-list-ul': faListUl,
    'fas fa-sign-in-alt': faSignInAlt,
    'fas fa-poll': faPollPeople,
    'fas fa-info-circle': faInfoCircle,
    'far fa-lightbulb': faLightbulb,
    'fas fa-hourglass-half': faHourglassHalf,
    'fas fa-ticket-simple': faTickets,
    'fa-brands fa-twitch': faTwitch,
    'fa-brands fa-youtube': faYoutube,
    'fa-brands fa-twitter': faXTwitter,
    'fa-brands fa-tiktok': faTiktok,
    'fa-brands fa-instagram': faInstagram,
    'fa-brands fa-facebook': faFacebook,
    'fa-brands fa-reddit': faReddit,
    'fas fa-door-open': faDoorOpen,
    'fas fa-gears': faGears,
    'fa-user-tie': faUserTie,
    'fa-brands fa-threads': faThreads,
    'fa-brands fa-mastodon': faMastodon,
    'far fa-gear': faUserGear,
    'far fa-terminal': faTerminal,
    'fa-solid fa-border-all': faBorderAll,
    'fa-solid fa-comments-question-check': faCommentsQuestionCheck,
    'fa-solid fa-icons': faIcons,
    'fa-solid fa-check-to-slot': faCheckToSlot,
    'fa-solid fa-users-viewfinder': faUsersViewfinder,
    'fa-solid fa-tags': faTags,
    'fa-solid fa-volume-high': faVolumeHigh,
    'fa-solid fa-user-tag': faUserTag,
    'fas fa-circle-chevron-up': faCircleChevronUp,
    'fa-solid fa-table-cells': faTableCells,
    'fa-solid fa-clipboard-check': faClipboardCheck,
    'fas fa-palette': faPalette,
    'fa-solid fa-puzzle-piece': faPuzzlePiece,
    'fas fa-gun': faGun,
    'fa-solid fa-flag': faFlag,
    'fas fa-ranking-stars': faRankingStar,
    'fas fa-star': faStar,
    'fas fa-smile': faFaceSmile,
    'fas fa-thumbtack': faThumbtack,
    'far fa-comment-dots': faCommentsQuestion,
    'fa-solid fa-file-circle-check': faFileCirclePlus
};

export default function ModuleIcon({icon, className, width = 23, hMe}) {
    if (icon === 'top-gg') return <svg viewBox="120 120 580 580" className={`${className} ${hMe ? 'h-5' : 'h-10'}`}
                                       width={width - 4}>
        <path fill="white"
              d="M655.711 247H330.71v325h66.403a96.097 96.097 0 0096.097-96.098V409.5h66.403a96.102 96.102 0 0096.098-96.098V247zM144 247h162.5v162.5H193.657a49.49 49.49 0 01-49.492-49.492L144 247z"></path>
    </svg>;
    return <FontAwesomeIcon icon={icons[icon] || faFolder} width={width} className={className}/>;
}